name: peer
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - absl-py
  - pyparsing
  - pillow=6.1
  - pip:
    - termcolor
    - mujoco
    - git+git://github.com/deepmind/dm_control.git
    - git+git://github.com/1nadequacy/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - torchvision
    - scikit-image
    - pynvml
    - atari-py
    - opencv-python
    - plotly
    - torchvision
    - kornia
    - tqdm